#!/usr/bin/env bash

set -e

CONTAINER_NAME_SCRIPT="local_sherpa_install_script"
CONTAINER_NAME_HOMEBREW="local_sherpa_install_homebrew"

# shellcheck disable=SC2317
cleanup() {
  docker compose down install_script install_homebrew
}

trap cleanup EXIT

TESTS_FAILED=0

docker compose up -d install_script
docker exec -it $CONTAINER_NAME_SCRIPT bash -i ./tests/install/update/script || TESTS_FAILED=1

docker compose up -d install_homebrew
docker exec -it $CONTAINER_NAME_HOMEBREW bash -i /app/tests/install/update/homebrew || TESTS_FAILED=1

if [ "$TESTS_FAILED" -eq 0 ]; then
  echo -e "\033[32mWorks!\033[0m"
else
  echo -e "\033[31mTest suite failed.\033[0m"
fi

exit $TESTS_FAILED
