#!/usr/bin/env bash

set -e

HOMEBREW_CONTAINER_NAME="local_sherpa_homebrew_install"

# shellcheck disable=SC2317
cleanup() {
  docker-compose down homebrew_install
}

trap cleanup EXIT

TESTS_FAILED=0

docker-compose up -d homebrew_install
docker exec -it $HOMEBREW_CONTAINER_NAME bash -i /app/tests/install/local_build/homebrew || TESTS_FAILED=1

if [ "$TESTS_FAILED" -eq 0 ]; then
  echo -e "\033[32mWorks!\033[0m"
else
  echo -e "\033[31mTest suite failed.\033[0m"
fi

exit $TESTS_FAILED
