#!/usr/bin/env bash

set -e

UBUNTU_CONTAINER_NAME="local-sherpa-ubuntu-install-uninstall"
HOMEBREW_CONTAINER_NAME="local-sherpa-homebrew-install-uninstall"
EXIT_CODE=0

cleanup() {
  docker-compose down ubuntu_install_uninstall homebrew_install_uninstall
}

trap cleanup EXIT

TESTS_FAILED=0

docker-compose up -d ubuntu_install_uninstall
docker exec -it $UBUNTU_CONTAINER_NAME bash -i ./tests/install_uninstall/automated_production || TESTS_FAILED=1

docker-compose up -d homebrew_install_uninstall
docker exec -it $HOMEBREW_CONTAINER_NAME bash -i /app/tests/install_uninstall/homebrew_local || TESTS_FAILED=1

docker-compose down homebrew_install_uninstall
docker-compose up -d homebrew_install_uninstall
docker exec -it $HOMEBREW_CONTAINER_NAME bash -i /app/tests/install_uninstall/homebrew_production || TESTS_FAILED=1

if [ "$TESTS_FAILED" -eq 0 ]; then
  echo -e "\033[32mWorks!\033[0m"
else
  echo -e "\033[31mTest suite failed.\033[0m"
fi

exit $TESTS_FAILED
