#!/usr/bin/env bash

shell_name="$1"

case $shell_name in
  bash)
    shell_name="Bash"
    # We run the tests in interactive mode to be able to test aliases
    shell_command="bash --noprofile --norc -i"
    ;;
  zsh)
    shell_name="Zsh"
    shell_command="zsh"
    ;;
  *)
    echo "Unknown shell: $shell_name"
    exit 1
    ;;
esac

echo "=============================== Shell: $shell_name =============================="
stderr_file=$(mktemp)
all_tests_passed=true

run_single_test() {

  echo "== Running $test_file"
  $shell_command "$test_file" 2>> "$stderr_file" || all_tests_passed=false
  echo ""
}

run_all_tests() {
  local _test_files=(tests/**/*_test.sh)

  for file in "${_test_files[@]}" ; do
    echo "== Running $file"
    $shell_command "$file" 2>> "$stderr_file" || all_tests_passed=false

    echo ""
  done
}


test_file=$2
if [ -n "$test_file" ]; then
  run_single_test
else
  run_all_tests
fi

if $all_tests_passed; then
  echo -e "\033[32mAll tests passed successfully!\033[0m"
else
  echo -e "\033[31mFailed examples:\033[0m"
  while IFS= read -r line; do
    echo "  $line" >&2
  done < "$stderr_file"
  rm "$stderr_file"

  exit 1
fi
