#!/usr/bin/env bash

shell_name="$1"

case $shell_name in
  bash)
    shell_name="Bash"
    # We run the tests in interactive mode to be able to test aliases
    shell_command="bash --noprofile --norc -i"
    ;;
  zsh)
    shell_name="Zsh"
    shell_command="zsh"
    ;;
  *)
    echo "Unknown shell: $shell_name"
    exit 1
    ;;
esac

echo "=============================== Shell: $shell_name =============================="

run_single_test() {
  local _tests_passed=true

  echo "== Running $test_file"
  $shell_command $test_file || _tests_passed=false
  echo ""

  if $_tests_passed; then
    echo -e "\033[32mTest passed successfully!\033[0m"
  else
    echo -e "\033[31mTest failed.\033[0m"
    exit 1
  fi
}

run_all_tests() {
  local _test_files=(tests/**/*_test.sh)
  local _all_tests_passed=true

  for file in "${_test_files[@]}" ; do
    echo "== Running $file"
    $shell_command $file || _all_tests_passed=false
    echo ""
  done

  if $_all_tests_passed; then
    echo -e "\033[32mAll tests passed successfully!\033[0m"
  else
    echo -e "\033[31mSome tests failed.\033[0m"
    exit 1
  fi
}


test_file=$2
if [ -n "$test_file" ]; then
  run_single_test
else
  run_all_tests
fi
