services:
  ubuntu_dev:
    hostname: ubuntu_dev
    build:
      context: .
      dockerfile: dockerfiles/ubuntu_dev.dockerfile
    container_name: local_sherpa_ubuntu_dev
    volumes:
      - .:/app
      - ./tmp/ubuntu_dev_container/.zsh_aliases:/root/.zsh_aliases
      - ./tmp/ubuntu_dev_container/.bash_aliases:/root/.bash_aliases
    stdin_open: true
    tty: true

  ubuntu_test:
    hostname: ubuntu_test
    build:
      context: .
      dockerfile: dockerfiles/ubuntu_test.dockerfile
    container_name: local_sherpa_ubuntu_test
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  ubuntu_install:
    hostname: ubuntu_install
    build:
      context: .
      dockerfile: dockerfiles/ubuntu_install.dockerfile
    container_name: local_sherpa_ubuntu_install
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  homebrew_install:
    image: homebrew/brew
    hostname: homebrew_install
    container_name: local_sherpa_homebrew_install
    volumes:
      - .:/app
      - ./tmp/homebrew:/homebrew
    environment:
      - HOMEBREW_NO_ANALYTICS=1
      - HOMEBREW_NO_AUTO_UPDATE=1
      - SHERPA_VERSION
    stdin_open: true
    tty: true

  min_shell_versions_ubuntu:
    hostname: min_shell_versions_ubuntu
    build:
      context: .
      dockerfile: dockerfiles/min_shell_versions_ubuntu.dockerfile
    container_name: local_sherpa_min_shell_versions_ubuntu
    volumes:
      - .:/app
    stdin_open: true
    tty: true
