services:
  ubuntu_dev:
    hostname: ubuntu_dev
    build:
      context: .
      dockerfile: dockerfiles/ubuntu_dev.dockerfile
    container_name: local_sherpa_ubuntu_dev
    volumes:
      - .:/app
      - ./tmp/ubuntu_dev_container/.zsh_aliases:/root/.zsh_aliases
      - ./tmp/ubuntu_dev_container/.bash_aliases:/root/.bash_aliases
    stdin_open: true
    tty: true

  ubuntu_test:
    hostname: ubuntu_test
    build:
      context: .
      dockerfile: dockerfiles/ubuntu_test.dockerfile
    container_name: local_sherpa_ubuntu_test
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  install_script:
    hostname: install_script
    build:
      context: .
      dockerfile: dockerfiles/install.dockerfile
    container_name: local_sherpa_install_script
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  install_homebrew:
    image: homebrew/brew
    hostname: install_homebrew
    container_name: local_sherpa_install_homebrew
    volumes:
      - .:/app
      - ./tmp/homebrew:/homebrew
    environment:
      - HOMEBREW_NO_ANALYTICS=1
      - HOMEBREW_NO_AUTO_UPDATE=1
      - SHERPA_VERSION
    stdin_open: true
    tty: true

  ubuntu_min_shell_versions:
    hostname: ubuntu_min_shell_versions
    build:
      context: .
      dockerfile: dockerfiles/ubuntu_min_shell_versions.dockerfile
    container_name: local_sherpa_ubuntu_min_shell_versions
    volumes:
      - .:/app
    stdin_open: true
    tty: true
