services:
  ubuntu:
    hostname: ubuntu
    build:
      context: .
      dockerfile: dockerfiles/ubuntu.dockerfile
    container_name: local-sherpa-ubuntu
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  ubuntu_install:
    hostname: ubuntu_install
    build:
      context: .
      dockerfile: dockerfiles/ubuntu_install.dockerfile
    container_name: local_sherpa_ubuntu_install
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  homebrew_install:
    image: homebrew/brew
    hostname: homebrew_install
    container_name: local_sherpa_homebrew_install
    volumes:
      - .:/app
      - ./tmp/homebrew:/homebrew
    environment:
      - HOMEBREW_NO_ANALYTICS=1
      - HOMEBREW_NO_AUTO_UPDATE=1
      - SHERPA_VERSION
    stdin_open: true
    tty: true

  min-shell-versions-ubuntu:
    hostname: min-shell-versions-ubuntu
    build:
      context: .
      dockerfile: dockerfiles/min_shell_versions_ubuntu.dockerfile
    container_name: local-sherpa-min-shell-versions-ubuntu
    volumes:
      - .:/app
    stdin_open: true
    tty: true
