services:
  ubuntu:
    hostname: ubuntu
    build:
      context: .
      dockerfile: dockerfiles/ubuntu.dockerfile
    container_name: local-sherpa-ubuntu
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  ubuntu_install_uninstall:
    hostname: ubuntu_install_uninstall
    build:
      context: .
      dockerfile: dockerfiles/ubuntu_install_uninstall.dockerfile
    container_name: local-sherpa-ubuntu-install-uninstall
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  min-shell-versions-ubuntu:
    hostname: min-shell-versions-ubuntu
    build:
      context: .
      dockerfile: dockerfiles/min_shell_versions_ubuntu.dockerfile
    container_name: local-sherpa-min-shell-versions-ubuntu
    volumes:
      - .:/app
    stdin_open: true
    tty: true
