services:
  dev:
    hostname: dev
    build:
      context: .
      dockerfile: dockerfiles/dev.dockerfile
    container_name: local_sherpa_dev
    volumes:
      - .:/app
      - ./tmp/dev_container/.zsh_aliases:/root/.zsh_aliases
      - ./tmp/dev_container/.bash_aliases:/root/.bash_aliases
    stdin_open: true
    tty: true

  test:
    hostname: test
    build:
      context: .
      dockerfile: dockerfiles/test.dockerfile
    container_name: local_sherpa_test
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  install_script:
    hostname: install_script
    build:
      context: .
      dockerfile: dockerfiles/install.dockerfile
    container_name: local_sherpa_install_script
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  install_homebrew:
    image: homebrew/brew
    hostname: install_homebrew
    container_name: local_sherpa_install_homebrew
    volumes:
      - .:/app
      - ./tmp/homebrew:/homebrew
    environment:
      - HOMEBREW_NO_ANALYTICS=1
      - HOMEBREW_NO_AUTO_UPDATE=1
      - SHERPA_VERSION
    stdin_open: true
    tty: true

  min_shell_versions:
    hostname: min_shell_versions
    build:
      context: .
      dockerfile: dockerfiles/min_shell_versions.dockerfile
    container_name: local_sherpa_min_shell_versions
    volumes:
      - .:/app
    stdin_open: true
    tty: true
