services:
  ubuntu:
    hostname: ubuntu
    build:
      context: .
      dockerfile: dockerfiles/ubuntu.dockerfile
    container_name: local-sherpa-ubuntu
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  ubuntu_install_uninstall:
    hostname: ubuntu_install_uninstall
    build:
      context: .
      dockerfile: dockerfiles/ubuntu_install_uninstall.dockerfile
    container_name: local-sherpa-ubuntu-install-uninstall
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  homebrew_install_uninstall:
    image: homebrew/brew
    container_name: local-sherpa-homebrew-install-uninstall
    volumes:
      - .:/app
      - ./tmp/homebrew:/homebrew
    environment:
      - HOMEBREW_NO_ANALYTICS=1
      - HOMEBREW_NO_AUTO_UPDATE=1
      - SHERPA_VERSION
    stdin_open: true
    tty: true

  min-shell-versions-ubuntu:
    hostname: min-shell-versions-ubuntu
    build:
      context: .
      dockerfile: dockerfiles/min_shell_versions_ubuntu.dockerfile
    container_name: local-sherpa-min-shell-versions-ubuntu
    volumes:
      - .:/app
    stdin_open: true
    tty: true
