#!/usr/bin/env bash

TESTS_PASSED=true

./test_bash "$@" || TESTS_PASSED=false
echo ""
echo ""

./test_zsh "$@" || TESTS_PASSED=false

echo ""

if $TESTS_PASSED; then
  echo -e "\033[32mTest suite passed successfully!\033[0m"
else
  echo -e "\033[31mTest suite failed.\033[0m"
  exit 1
fi
