#!/usr/bin/env bash

set -e

DOCKER_CONTAINER_NAME="local_sherpa_test"

# Start the container if it's not running
if ! docker ps | grep -q $DOCKER_CONTAINER_NAME; then
  docker compose up -d test
fi

DOCKER_EXEC="docker exec -it $DOCKER_CONTAINER_NAME"
TESTS_PASSED=true

echo "**************** Running in Ubuntu ****************"

$DOCKER_EXEC ./tests/test_bash "$@" || TESTS_PASSED=false
echo ""
echo ""

$DOCKER_EXEC ./tests/test_zsh "$@" || TESTS_PASSED=false

echo ""

if $TESTS_PASSED; then
  echo -e "\033[32mTest suite passed successfully!\033[0m"
  exit 0
else
  echo -e "\033[31mTest suite failed.\033[0m"
  exit 1
fi
