#!/usr/bin/env bash

# Test Suite Runner
#
# This script runs all the tests on the host for all the supported shells.
# It supports running a specific test file or all the test files.
#
# Usage:
#   ./tests/test_all [test_file]
#
# Arguments:
#   test_file : (Optional) Specific test file to run. If not provided, all the
#               test files will be executed for all the supported shells.
#
# Example Usage:
#   ./tests/test_all
#   ./tests/test_all tests/example_test.sh
#
# Exit Codes:
#   0 : The test suite passed passed successfully.
#   1 : It failed.

set -e

# Check if all shell executables are available
for shell_executable in zsh bash; do
  if ! which "$shell_executable" > /dev/null; then
    echo "!! This test requires the ${shell_executable} executable !!"
    exit 1
  fi
done

TESTS_PASSED=true

./tests/test_bash "$@" || TESTS_PASSED=false
echo ""
echo ""

./tests/test_zsh "$@" || TESTS_PASSED=false

echo ""

if $TESTS_PASSED; then
  echo -e "\033[32mTest suite passed successfully!\033[0m"
else
  echo -e "\033[31mTest suite failed.\033[0m"
  exit 1
fi
